package cn.econets.blossom.module.system.service.errorcode;


import cn.econets.blossom.framework.common.pojo.PageResult;
import cn.econets.blossom.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import cn.econets.blossom.module.system.api.errorcode.dto.ErrorCodeRespDTO;
import cn.econets.blossom.module.system.controller.admin.errorcode.vo.ErrorCodePageReqVO;
import cn.econets.blossom.module.system.controller.admin.errorcode.vo.ErrorCodeSaveReqVO;
import cn.econets.blossom.module.system.dal.dataobject.errorcode.ErrorCodeDO;

import javax.validation.Valid;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Error code Service Interface
 *
 */
public interface ErrorCodeService {

    /**
     * Automatically create error code
     *
     * @param autoGenerateDTOs Error code information
     */
    void autoGenerateErrorCodes(@Valid List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

    /**
     * Incrementally obtain error code array
     *
     * If minUpdateTime When empty，Get all error codes
     *
     * @param applicationName Application name
     * @param minUpdateTime Minimum update time
     * @return Error code array
     */
    List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime);

    /**
     * Create error code
     *
     * @param createReqVO Create information
     * @return Number
     */
    Long createErrorCode(@Valid ErrorCodeSaveReqVO createReqVO);

    /**
     * Update error code
     *
     * @param updateReqVO Update information
     */
    void updateErrorCode(@Valid ErrorCodeSaveReqVO updateReqVO);

    /**
     * Delete error code
     *
     * @param id Number
     */
    void deleteErrorCode(Long id);

    /**
     * Get error code
     *
     * @param id Number
     * @return Error code
     */
    ErrorCodeDO getErrorCode(Long id);

    /**
     * Get error code paging
     *
     * @param pageReqVO Paged query
     * @return Error code paging
     */
    PageResult<ErrorCodeDO> getErrorCodePage(ErrorCodePageReqVO pageReqVO);

}
