spring:
  application:
    name: blossom-server
  profiles:
    active: dev

  main:
    allow-circular-references: true # Allow circular dependencies，Because the project is a three-tier architecture，This situation cannot be avoided。

  # Servlet Configuration
  servlet:
    # File upload related configuration items
    multipart:
      max-file-size: 16MB # Single file size
      max-request-size: 32MB # Set the total uploaded file size
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # Solved SpringFox with SpringBoot 2.6.x Incompatible issues，See SpringFoxHandlerProviderBeanPostProcessor Class
  #    throw-exception-if-no-handler-found: true # 404 Throw exception on error，Convenient for unified processing
  #    static-path-pattern: /static/** # Static resource path; Attention：If not configured，Then throw-exception-if-no-handler-found Not effective！！！ TODO Cannot configure，Will lead to swagger Not effective

  # Jackson Configuration item
  jackson:
    serialization:
      write-dates-as-timestamps: true # Settings Date Format，Use timestamp
      write-date-timestamps-as-nanoseconds: false # Set not to use nanoseconds Format。For example 1611460870.401，But directly 1611460870401
      write-durations-as-timestamps: true # Settings Duration Format，Use timestamp
      fail-on-empty-beans: false # Allow serialization without attributes Bean

  # Cache Configuration item
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # Set the expiration time to 1 Hours

--- #################### Interface document configuration ####################
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true # See https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param Document

knife4j:
  enable: true
  setting:
    language: zh_cn

# MyBatis Plus Configuration items
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # Although the default is true ，But it still shows that you need to specify it。
  global-config:
    db-config:
      id-type: NONE # “Intelligent”Mode，Based on IdTypeEnvironmentPostProcessor + Data source type，Automatically adapt to AUTO、INPUT Mode。
      #      id-type: AUTO # Self-increment ID，Suitable for MySQL Databases that are directly incremented
      #      id-type: INPUT # User input ID，Suitable for Oracle、PostgreSQL、Kingbase、DB2、H2 Database
      #      id-type: ASSIGN_ID # Allocation ID，Use snowflake algorithm by default。Attention，Oracle、PostgreSQL、Kingbase、DB2、H2 Database time，Need to remove the entity class @KeySequence Annotation
      logic-delete-value: 1 # Logically deleted value(Default is 1)
      logic-not-delete-value: 0 # Logical undeleted values(Default is 0)
    banner: false # Close the console Banner Print
  type-aliases-package: ${application.info.base-package}.module.*.dal.dataobject
  encryptor:
    password: XDV71a+xqStEA3WH # Secret key for encryption and decryption，Available https://www.imaegoo.com/2020/aes-key-generator/ Website Generation

mybatis-plus-join:
  banner: true # Close the console Banner Print

# Spring Data Redis Configuration
spring:
  data:
    redis:
      repositories:
        enabled: false # Project not used Spring Data Redis of Repository，So just disable it，Ensure startup speed

--- #################### Verification code related configuration ####################
aj:
  captcha:
    jigsaw: classpath:images/jigsaw # Slide verification，Basemap path，If not configured, the default image will be used；With classpath: Beginning，Take resource Directory path
    pic-click: classpath:images/pic-click # Slide verification，Basemap path，If not configured, the default image will be used；With classpath: Beginning，Take resource Directory path
    cache-type: redis # Cache local/redis...
    cache-number: 1000 # local Cache threshold,Reach this value，Clear cache
    timing-clear: 180 # localClear expired cache regularly(Unit: seconds),Set to0Represents not executed
    type: blockPuzzle # Verification code type defaultInstantiate both。 blockPuzzle Sliding Block Puzzle clickWord Text selection
    water-mark: ${spring.application.name} # Watermark text in the lower right corner，Available https://tool.chinaz.com/tools/unicode.aspx Chinese to Chinese Unicode，Linux May need to be transferred unicode
    interference-options: 0 # Sliding interference items(0/1/2)
    req-frequency-limit-enable: false # Is the one-minute limit on the number of interface requests enabled? true|false
    req-get-lock-limit: 5 # Verification failed 5 times，getInterface locked
    req-get-lock-seconds: 10 # After verification fails，Lock time interval
    req-get-minute-limit: 30 # get Interface request limit within one minute
    req-check-minute-limit: 60 # check Interface request limit within one minute
    req-verify-minute-limit: 60 # verify Interface request limit within one minute

--- #################### Message queue related ####################
# rocketmq Configuration item，Corresponding RocketMQProperties Configuration Class
rocketmq:
  # Producer Configuration item
  producer:
    group: ${spring.application.name}_PRODUCER # Producer Grouping

spring:
  # Kafka Configuration item，Corresponding KafkaProperties Configuration Class
  kafka:
    # Kafka Producer Configuration item
    producer:
      acks: 1 # 0-No answer。1-leader Answer。all-All leader Maki follower Answer。
      retries: 3 # When sending fails，Number of times to retry sending
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Message value Serialization
    # Kafka Consumer Configuration item
    consumer:
      auto-offset-reset: earliest # Set the initial consumption progress of the consumer group to earliest 。Please refer to the blog https://blog.csdn.net/lishuangzhe7047/article/details/74530417 Understanding
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    # Kafka Consumer Listener Listener Configuration
    listener:
      missing-topics-fatal: false # When the subject monitored by the consumer monitoring interface does not exist，Will report an error by default。So by setting it to false ，Solve the error

--- #################### Related configuration ####################
application:
  captcha:
    enable: true # Verification code switch，Default is true
  codegen:
    base-package: ${application.info.base-package}
    db-schemas: ${spring.datasource.dynamic.datasource.master.name}
    front-type: 10 # Front-end template type，See CodegenFrontTypeEnum Enumeration class
  # Error code related configuration items
  error-code:
    constants-class-list:
      - cn.econets.blossom.module.infrastructure.enums.ErrorCodeConstants
      - cn.econets.blossom.module.system.enums.ErrorCodeConstants
      - cn.econets.blossom.module.member.enums.ErrorCodeConstants
      - cn.econets.blossom.module.pay.enums.ErrorCodeConstants
      - cn.econets.blossom.module.mp.enums.ErrorCodeConstants
      - cn.econets.blossom.module.bpm.enums.ErrorCodeConstants
  info:
    base-package: cn.econets.blossom
    version: 1.0.1
  security:
    permit-all_urls:
      - /admin-api/open/** # Open interface，No login required
  # Configuration items related to SMS verification codes
  sms-code:
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 # Configure here 9999 The reason is，Convenient for testing。
    end-code: 9999 # Configure here 9999 The reason is，Easy to test。
  swagger:
    title: ${spring.application.name}Interface Documentation
    description: Provide management background、User App All functions
    version: ${application.info.version}
    url: ${application.web.admin-ui.url}
    email: ryximu@qq.com
    license: MIT
    license-url: https://github.com/EcoNetsTech/econets-vue.git
  # Multi-tenant related configuration items
  tenant:
    enable: true
    ignore-urls:
      - /admin-api/system/tenant/get-id-by-name # Get tenants based on name，Tenant number is not allowed
      - /admin-api/system/tenant/get-by-website # Get tenants based on domain name，Tenant number is not allowed
      - /admin-api/system/captcha/get # Get the image verification code，Not related to tenants
      - /admin-api/system/captcha/check # Verify the image verification code，Not related to tenants
      - /admin-api/infra/file/*/get/** # Get the picture，Not related to tenants
      - /admin-api/system/sms/callback/* # SMS callback interface，Cannot provide tenant number
      - /admin-api/pay/notify/** # Payment callback notification，Does not carry tenant number
      - /admin-api/mp/open/** # WeChat public account open platform，WeChat callback interface，Cannot carry tenant number
    ignore-tables:
      - system_tenant
      - system_tenant_package
      - system_tenant_package_menu
      - system_dict_data
      - system_dict_type
      - system_error_code
      - system_menu
      - system_sms_channel
      - system_sms_template
      - system_sms_log
      - system_sensitive_word
      - system_oauth2_client
      - system_mail_account
      - system_mail_template
      - system_mail_log
      - system_notify_template
      - infra_codegen_column
      - infra_codegen_table
      - infra_test_demo
      - infra_config
      - infra_file_config
      - infra_file
      - infra_file_content
      - infra_job
      - infra_job_log
      - infra_job_log
      - infra_data_source_config
      - jimu_dict
      - jimu_dict_item
      - jimu_report
      - jimu_report_data_source
      - jimu_report_db
      - jimu_report_db_field
      - jimu_report_db_param
      - jimu_report_link
      - jimu_report_map
      - jimu_report_share
      - report_ureport_data
      - rep_demo_dxtj
      - rep_demo_employee
      - rep_demo_gongsi
      - rep_demo_jianpiao
      - tmp_report_data_1
      - tmp_report_data_income
    ignore-cache:
      - permission_menu_ids
  trade:
    order:
      app-id: 1 # Merchant Number
      pay-expire-time: 2h # Payment expiration date
      receive-expire-time: 14d # Expiration date of received goods
      comment-expire-time: 7d # Expiration time of comment
    express:
      client: kd_niao
      kd-niao:
        api-key: cb022f1e-48f1-4c4a-a723-9001ac9676b8
        business-id: 1809751
      kd100:
        key: pLXUGAwK5305
        customer: E77DF18BE109F454A5CD319E44BF5177
  web:
    admin-ui:
      url: https://www.ximu233.com # Admin Management Backend UI Address


debug: false
