package cn.econets.blossom.module.system.api.errorcode;

import cn.econets.blossom.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import cn.econets.blossom.module.system.api.errorcode.dto.ErrorCodeRespDTO;

import javax.validation.Valid;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Error code Api Interface
 *
 */
public interface ErrorCodeApi {

    /**
     * Automatically create error code
     *
     * @param autoGenerateDTOs Error code information
     */
    void autoGenerateErrorCodeList(@Valid List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

    /**
     * Incrementally obtain error code array
     *
     * If minUpdateTime When empty，Get all error codes
     *
     * @param applicationName Application name
     * @param minUpdateTime Minimum update time
     * @return Error code array
     */
    List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime);

}
