package cn.econets.blossom.module.bpm.enums.task;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Process Task -- Signature type enumeration type
 */
@Getter
@AllArgsConstructor
public enum BpmTaskAddSignTypeEnum {

    /**
     * Add signature forward，Preliminary tasks need to be approved，Returned to the original approver
     */
    BEFORE("before", "Add signature forward"),
    /**
     * Add signature to the back，All post-tasks need to be approved，Only then it will pass the original approver node
     */
    AFTER("after", "Add signature to the back"),
    /**
     * Transition state when creating a post-signature，Used to control the task status generated by the backward signature
     */
    AFTER_CHILDREN_TASK("afterChildrenTask", "Subtasks generated by adding signatures later");

    private final String type;

    private final String desc;

    public static String formatDesc(String type) {
        for (BpmTaskAddSignTypeEnum value : values()) {
            if (value.type.equals(type)) {
                return value.desc;
            }
        }
        return null;
    }

}
    